### ISSUE TITLE
Include gender article for returned nouns

### ISSUE THREAD

**Issue by cdunklau** [socksy/dictbot#3]
I'm not sure how tricky this is, but I wanted to get people thinking about it. Dictbot should return German nouns with the proper gender noted.

**Comment by socksy** [comment]
This is a good idea. It seems that bab.la returns a {f} or {m} after a noun, which is tagged with "masculine" or "feminine" in the HTML. I'll investigate in the next few days.

**Comment by socksy** [comment]
I don't even remember creating this repo. I guess it doesn't really matter any more.
